/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AiOption: typeof import('./src/components/home/subpages/aiOption.vue')['default']
    ChatFrame: typeof import('./src/components/home/subpages/chatFrame.vue')['default']
    ChatOp: typeof import('./src/components/home/subpages/chatOp.vue')['default']
    ChatOperate: typeof import('./src/components/home/subpages/chatOperate.vue')['default']
    ChatOption: typeof import('./src/components/home/subpages/chatOption.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    InputBox: typeof import('./src/components/home/subpages/messageFrame/inputBox.vue')['default']
    Menu: typeof import('./src/components/home/menu.vue')['default']
    MessageFrame: typeof import('./src/components/home/subpages/messageFrame.vue')['default']
    OpChat: typeof import('./src/components/home/subpages/opChat.vue')['default']
    Operate: typeof import('./src/components/home/subpages/Operate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChat: typeof import('./src/components/home/subpages/chatFrame/singleChat.vue')['default']
    SingleMessage: typeof import('./src/components/home/subpages/messageFrame/singleMessage.vue')['default']
  }
}
